workspace = { members = [ "CH-5/ex-10","CH-5/ex-9-area-of-rectangle", "CH-7/restaurant"] }
[package]
name = "rust-book"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
